language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: remembranza
  api_key:
    secure: kom0jAg9pCM2xiNBinntwjlWnt6D7W7pEbYOzr3ux3DfuYuqmb/SMcOwycHhL03vz+Mu5T4C37swaNor7JBryN23jOuloQ+nCzAttUrmgP9gH1W1tGVpENOgNltqJBvk/2EaBDbTE1TVoIyCqSrOyir9crfd5q7qF4DM2X2ggQ5a/wt07Wi3NRMzESB47IfYKlCvU3dYcro+H+IvTMPUi5XMqhn64dBOlEvkT2Ed8nmmmcwWS9g+IitSn81T1DrhQR+epqQkiKN78MAGUE+LbRJj/Lu+USAaXN+zBzFQA4UCyAReOReJ6Apu+6IIq9ok9ifL58KaRNEu6UHH+fGu+H2E6i8IDQJrc9QV3phBLxIAO5O2IrtXT2Hkr7oSWSAOj56jDWevwLIVJJhNrIO1BgsTcOkcIpRxO+dU3DBaW6xWCJYfHnPb3JsvCMl+t5LQ5R2xtjE+0HcsN+qnKg5HPZ1/Aljghb6UL/NpiyaXomNBWwP6md3fYRwb+tvVv9LFnT60T+XSK6KNTwJEGg7JdjIZ3f0S8eE9FKtSnRWf9guQZ8h8lflFyOoMOZRcZbky5skLNDvJkDI9KaAeGf642Ocpvi4amGYRUDU6uvKtv+vY14wFpSJoi2ugRWhCdb5JzHsTnaKvKK4OtwjK4yJczSkWlfUPFHk93tmC3ATemnc=
